# Generated by Django 4.1 on 2023-07-07 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_alter_book_options_alter_book_autor_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "permissions": [
                    ("development", "Permiso como Desarrollador"),
                    ("scrum_master", "Permiso como scrum_master"),
                    ("Product_owner", "Permiso como Product_Owner"),
                ],
                "verbose_name": "Libro",
                "verbose_name_plural": "Libros",
            },
        ),
    ]
