# Generated by Django 4.1 on 2023-07-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehiculo", "0005_remove_vehiculo_condicion_precio"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiculo",
            name="condicion_precio",
            field=models.CharField(default="sin precio", max_length=20),
        ),
    ]
