# Generated by Django 4.1 on 2023-07-20 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehiculo", "0006_vehiculo_condicion_precio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehiculo",
            name="condicion_precio",
        ),
    ]
