# Generated by Django 4.2.3 on 2023-07-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField(max_length=255)),
            ],
        ),
    ]
