# Generated by Django 4.1 on 2023-08-05 01:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos_del_proyecto", "0003_agregacion_de_relacion_y_campos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="f_vencimiento",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2015, 1, 1)
                    )
                ],
            ),
        ),
    ]
